#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "$ROOT"

fail() {
  printf 'automation readiness check failed: %s\n' "$1" >&2
  exit 1
}

require_file() {
  local file="$1"
  [[ -f "$file" ]] || fail "missing required file: $file"
}

require_contains() {
  local file="$1"
  local expected="$2"
  grep -Fq "$expected" "$file" || fail "$file must contain: $expected"
}

require_absent() {
  local file="$1"
  local forbidden="$2"
  if grep -Fq "$forbidden" "$file"; then
    fail "$file must not contain: $forbidden"
  fi
}

require_file ".github/workflows/checks.yml"
require_file ".github/pull_request_template.md"
require_file ".gitignore"
require_file ".graphifyignore"
require_file "docs/automation/automation-readiness.md"
require_file "docs/automation/codex-use-cases-alignment.md"
require_file "docs/automation/graphify-resource-graph-scope.md"
require_file "docs/automation/parent-codex-supervision.md"
require_file "docs/automation/post-issue-ledger.md"
require_file "docs/automation/symphony-issue-workflow-template.md"
require_file "docs/automation/verified-operations.md"
require_file "docs/design/mtpro-complete-blueprint.md"
require_file "docs/planning/project-role-map.md"
[[ -d "docs/planning/projects" ]] || fail "missing required directory: docs/planning/projects"
require_file "docs/planning/projects/mtpro-guidance-plan.md"
require_file "docs/planning/projects/mtpro-runtime-research-workbench-v1-plan.md"
require_file "docs/planning/projects/mtpro-trading-validation-and-parity-hardening-plan.md"
require_file "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md"
require_file "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md"
require_file "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md"
require_file "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md"
[[ -d "docs/audit/inputs" ]] || fail "missing required directory: docs/audit/inputs"
require_file "docs/audit/inputs/mtpro-runtime-research-workbench-v1-stage-evidence.md"
require_file "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md"
require_file "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md"
require_file "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md"
require_file "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md"
require_file "docs/validation/eval-strategy.md"
require_file "docs/validation/latest-verification-summary.md"
require_file "docs/validation/macos-build-run-loop.md"
require_file "docs/validation/trading-validation-matrix.md"
require_file "docs/validation/validation-plan.md"
require_file "verification.md"

if find docs/validation -maxdepth 1 -type f -name 'mtp-*-stage-*' | grep -q .; then
  fail "Project stage evidence / audit input files must live under docs/audit/inputs/"
fi

require_contains ".github/workflows/checks.yml" "name: checks"
require_contains ".github/workflows/checks.yml" "bash checks/run.sh"

require_contains ".github/pull_request_template.md" "Linked Linear Issue"
require_contains ".github/pull_request_template.md" "Graphify 上下文和更新状态"
require_contains ".github/pull_request_template.md" "symphony-issue Handoff"
require_contains ".github/pull_request_template.md" ".codex/symphony-issue-handoff.json"
require_contains ".github/pull_request_template.md" "ready_for_review: true"
require_contains ".github/pull_request_template.md" "auto_merge_enabled: true"
require_contains ".github/pull_request_template.md" "Parent Codex Automation Supervision"
require_contains ".github/pull_request_template.md" "Post-Issue Ledger / 施工后记账"
require_contains ".github/pull_request_template.md" "GitHub PR Automation 门槛"
require_contains ".github/pull_request_template.md" "Pre-PR Codex Code Review"
require_contains ".github/pull_request_template.md" "Verified Operations"
require_contains ".github/pull_request_template.md" "详细中文注释"
require_contains ".github/pull_request_template.md" 'Required check: `checks`'
require_contains ".github/pull_request_template.md" "Merge method: squash"
require_contains ".github/pull_request_template.md" "WIP=1"

require_contains ".gitignore" ".codex/"
require_contains ".gitignore" "graphify-out/"
require_contains ".graphifyignore" ".codex/"
require_contains ".graphifyignore" "graphify-out/"
require_contains ".graphifyignore" "Sources/"
require_contains ".graphifyignore" "Tests/"

require_contains "docs/automation/automation-readiness.md" "WIP=1"
require_contains "docs/automation/automation-readiness.md" "Linear issue execution contract"
require_contains "docs/automation/automation-readiness.md" "不在文档中固定 current issue"
require_contains "docs/automation/automation-readiness.md" "symphony-issue path"
require_contains "docs/automation/automation-readiness.md" "symphony-issue active Project pointer"
require_contains "docs/automation/automation-readiness.md" "GitHub PR Automation"
require_contains "docs/automation/automation-readiness.md" "Codex use-cases alignment"
require_contains "docs/automation/codex-use-cases-alignment.md" "当前不引入独立 eval 框架"
require_contains "docs/automation/codex-use-cases-alignment.md" "代码中文注释规则"
require_contains "docs/automation/graphify-resource-graph-scope.md" "resource relationship graph"
require_contains "docs/automation/graphify-resource-graph-scope.md" "docs/validation/latest-verification-summary.md"
require_contains "docs/automation/graphify-resource-graph-scope.md" '完整 `verification.md` 默认不进入 Graphify context'
require_contains "docs/automation/graphify-resource-graph-scope.md" "Post-Issue Ledger"
require_contains "docs/automation/parent-codex-supervision.md" "host-side fallback"
require_contains "docs/automation/parent-codex-supervision.md" "Linear issue execution contract"
require_contains "docs/automation/parent-codex-supervision.md" "Linear Project / Issue 格式 Gate"
require_contains "docs/automation/parent-codex-supervision.md" "Project Planning Facilitator"
require_contains "docs/automation/parent-codex-supervision.md" "active Project pointer"
require_contains "docs/automation/parent-codex-supervision.md" 'docs/audit/<linear-project-slug>-stage-code-audit.md'
require_contains "docs/automation/parent-codex-supervision.md" '第一个 issue 和后续 issue 的 `Backlog` -> `Todo` 操作都归属父 Codex'
require_contains "docs/automation/parent-codex-supervision.md" "Human 确认 Project / Issue plan"
require_contains "docs/automation/parent-codex-supervision.md" "Stage Code Audit Report 落仓规则"
require_contains "docs/automation/parent-codex-supervision.md" 'docs/audit/<linear-project-slug>-stage-code-audit.md'
require_contains "docs/automation/parent-codex-supervision.md" 'Linear Project status 设置或确认为 `Completed`'
require_contains "docs/automation/parent-codex-supervision.md" 'type=completed'
require_contains "docs/automation/parent-codex-supervision.md" 'completedAt'
require_contains "docs/automation/parent-codex-supervision.md" '不能替代 Linear Project status `Completed`'
require_contains "docs/automation/parent-codex-supervision.md" "报告必须覆盖整个 Linear Project"
require_contains "docs/automation/parent-codex-supervision.md" 'Linear Project `Completed` evidence'
require_contains "docs/automation/parent-codex-supervision.md" "Root Docs Delta"
require_contains "docs/automation/parent-codex-supervision.md" "Root Docs Refresh Gate"
require_contains "docs/automation/parent-codex-supervision.md" "Current Phase Progress Bar"
require_contains "docs/automation/parent-codex-supervision.md" "当前阶段完成进度条"
require_contains "docs/automation/parent-codex-supervision.md" "Goal / Roadmap target progress"
require_contains "docs/automation/parent-codex-supervision.md" '基于当前 `GOAL.md` 和 `ROADMAP.md` 的目标切片计算'
require_contains "docs/automation/parent-codex-supervision.md" 'Project closure 数量必须单独输出为 `Project Closure Count`'
require_contains "docs/automation/parent-codex-supervision.md" 'Linear Project status 已设置或确认为 `Completed`'
require_contains "docs/automation/parent-codex-supervision.md" "Project Closure Count"
require_contains "docs/automation/parent-codex-supervision.md" "Goal / Roadmap Target Progress"
require_contains "docs/automation/parent-codex-supervision.md" 'Human + `@001 / PLN`'
require_contains "docs/automation/parent-codex-supervision.md" "Next Human Project Planning 必须读取该文件"
require_contains "docs/automation/parent-codex-supervision.md" "Role Alias Rule"
require_contains "docs/automation/parent-codex-supervision.md" '@002 = PAR'
require_contains "docs/automation/parent-codex-supervision.md" "给 @002 下 Codex 指令"
require_contains "docs/automation/parent-codex-supervision.md" "@002 Startup Runbook"
require_contains "docs/automation/parent-codex-supervision.md" "执行前检查"
require_contains "docs/automation/parent-codex-supervision.md" "更新 active Project pointer"
require_contains "docs/automation/parent-codex-supervision.md" "pointer 更新后二次 queue preview"
require_contains "docs/automation/parent-codex-supervision.md" "gate 通过后推进唯一 eligible issue 到 Todo"
require_contains "docs/automation/parent-codex-supervision.md" '不启动 `symphony-issue`'
require_contains "docs/automation/post-issue-ledger.md" "before_remove"
require_contains "docs/automation/post-issue-ledger.md" "read_only"
require_contains "docs/automation/symphony-issue-workflow-template.md" "稳定 workflow 本体"
require_contains "docs/automation/symphony-issue-workflow-template.md" "当前 active Project pointer"
require_contains "docs/automation/symphony-issue-workflow-template.md" "<active-linear-project-slug>"
require_contains "docs/automation/symphony-issue-workflow-template.md" "仓库文档不固定 current Project"
require_contains "docs/automation/symphony-issue-workflow-template.md" "Parent Codex 更新规则"
require_contains "docs/automation/symphony-issue-workflow-template.md" "@002 Startup Runbook"
require_contains "docs/automation/symphony-issue-workflow-template.md" "pointer 更新后再次执行 queue preview"
require_contains "docs/automation/symphony-issue-workflow-template.md" '自动推进唯一 eligible `Backlog` -> `Todo`'
require_contains "docs/automation/symphony-issue-workflow-template.md" "不为每个新 Project 复制一套 workflow"
require_contains "docs/automation/verified-operations.md" "Authorization Source"
require_contains "docs/automation/verified-operations.md" "Evidence Location"
require_contains "docs/planning/project-role-map.md" "系统架构"
require_contains "docs/planning/project-role-map.md" "Product"
require_contains "docs/planning/project-role-map.md" "Design"
require_contains "docs/planning/project-role-map.md" "Engineering"
require_contains "docs/planning/project-role-map.md" "Finance"
require_contains "docs/planning/project-role-map.md" "Operations"
require_contains "docs/planning/project-role-map.md" "QA"
require_contains "docs/planning/project-role-map.md" "Finance / Trading Domain Analyst"
require_contains "docs/planning/project-role-map.md" "Automation / Runtime Operations Engineer"
require_contains "docs/planning/project-role-map.md" "Project Planning Facilitator"
require_contains "docs/planning/project-role-map.md" "Role Alias Map"
require_contains "docs/planning/project-role-map.md" "三位数字编号和三字母角色代号等价"
require_contains "docs/planning/project-role-map.md" '角色编号只用于沟通压缩，不改变职责边界，不授权执行'
require_contains "docs/planning/project-role-map.md" '`000` | `AIE`'
require_contains "docs/planning/project-role-map.md" "AI Engineer"
require_contains "docs/planning/project-role-map.md" "当前 Codex 协作入口"
require_contains "docs/planning/project-role-map.md" '`001` | `PLN`'
require_contains "docs/planning/project-role-map.md" '`002` | `PAR`'
require_contains "docs/planning/project-role-map.md" '`003` | `PRD`'
require_contains "docs/planning/project-role-map.md" '`004` | `DSG`'
require_contains "docs/planning/project-role-map.md" '`005` | `ARC`'
require_contains "docs/planning/project-role-map.md" '`006` | `QAV`'
require_contains "docs/planning/project-role-map.md" '`007` | `OPS`'
require_contains "docs/planning/project-role-map.md" "Linear 外的 reference / root docs 角色"
require_contains "docs/planning/project-role-map.md" "symphony-issue、Codex Execution Agent 和 GitHub PR Automation 是流程工具 / 执行层 actor"
require_contains "docs/planning/project-role-map.md" "前端设计"
require_contains "docs/planning/project-role-map.md" "后端开发"
require_contains "docs/planning/project-role-map.md" "数据 / 持久化"
require_contains "docs/planning/project-role-map.md" "交易语义"
require_contains "docs/planning/project-role-map.md" "部署与运营"
require_contains "docs/planning/project-role-map.md" "不授权执行"
require_contains "docs/planning/project-role-map.md" "Complete Blueprint Design"
require_contains "docs/planning/project-role-map.md" "MTPRO Complete Blueprint Design"
require_contains "docs/planning/project-role-map.md" "Current Phase Progress Bar"
require_contains "docs/planning/project-role-map.md" "当前阶段完成进度条"
require_contains "docs/planning/project-role-map.md" 'Human + `@000 / AIE`'
require_contains "docs/planning/project-role-map.md" "Current Construction Scope"
require_contains "docs/planning/project-role-map.md" "Future Construction Zones"
require_contains "docs/planning/project-role-map.md" '不启动 `@002 / PAR`'
require_contains "docs/design/mtpro-complete-blueprint.md" "MTPRO Complete Blueprint Design"
require_contains "docs/design/mtpro-complete-blueprint.md" 'Human + `@000 / AIE`'
require_contains "docs/design/mtpro-complete-blueprint.md" "角色职责、Project 调度规则、阶段完成进度条和自动化 closure 规则不在本文档重复定义"
require_absent "docs/design/mtpro-complete-blueprint.md" "@000 / AIE 蓝图职责"
require_contains "docs/design/mtpro-complete-blueprint.md" "Final Product Blueprint"
require_contains "docs/design/mtpro-complete-blueprint.md" "System Architecture Blueprint"
require_contains "docs/design/mtpro-complete-blueprint.md" "Workbench / UX Blueprint"
require_contains "docs/design/mtpro-complete-blueprint.md" "Complete Capability Map"
require_contains "docs/design/mtpro-complete-blueprint.md" "Current Construction Scope"
require_contains "docs/design/mtpro-complete-blueprint.md" "Future Construction Zones"
require_contains "docs/design/mtpro-complete-blueprint.md" "Live / signed endpoint / broker / OMS"
require_contains "docs/design/mtpro-complete-blueprint.md" "Root Docs Delta Proposal"
require_contains "docs/design/mtpro-complete-blueprint.md" "Linear Planning Handoff"
require_contains "docs/design/mtpro-complete-blueprint.md" "不创建 Linear Project / Issue"
require_contains "docs/design/mtpro-complete-blueprint.md" '不推进 `Todo`'
require_contains "docs/design/mtpro-complete-blueprint.md" "不启动 Symphony"
require_contains "README.md" "docs/design/mtpro-complete-blueprint.md"
require_contains "AGENTS.md" "Complete Blueprint Design"
require_contains "AGENTS.md" "当前阶段完成进度条"
require_contains "AGENTS.md" "Goal / Roadmap Target Progress"
require_contains "AGENTS.md" "不写入蓝图文档"
require_contains "AGENTS.md" 'Human + `@000 / AIE`'
require_contains "AGENTS.md" "Future Construction Zones"
require_contains "AGENTS.md" '不启动 `@002 / PAR`'
for planning_record in \
  "docs/planning/projects/mtpro-guidance-plan.md" \
  "docs/planning/projects/mtpro-runtime-research-workbench-v1-plan.md" \
  "docs/planning/projects/mtpro-trading-validation-and-parity-hardening-plan.md" \
  "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" \
  "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" \
  "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" \
  "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md"; do
  require_contains "$planning_record" "Project name"
  require_contains "$planning_record" "Project goal"
  require_contains "$planning_record" "Scope"
  require_contains "$planning_record" "Non-goals"
  require_contains "$planning_record" "Issue order"
  require_contains "$planning_record" "Dependencies"
  require_contains "$planning_record" "Validation requirements"
  require_contains "$planning_record" "Evidence requirements"
  require_contains "$planning_record" "First executable issue candidate"
  require_contains "$planning_record" "WIP=1"
  require_contains "$planning_record" "Linear write boundary"
  require_contains "$planning_record" "Repository record boundary"
  require_contains "$planning_record" "完整 issue execution contract"
  require_contains "$planning_record" "本文档不授权执行"
done

require_contains "docs/planning/projects/mtpro-trading-validation-and-parity-hardening-plan.md" "MTPRO Trading Validation and Parity Hardening"
require_contains "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" "MTPRO Paper Session Runtime v1"
require_contains "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" "Parent Codex queue preflight rule"
require_contains "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" "不复制维护完整 Linear issue body"
require_contains "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" "不推进 Todo"
require_contains "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" "不启动 Symphony"
require_contains "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md" "Project 经 Human 确认并写入 Linear 后，由 Parent Codex queue preflight 自动判断唯一 eligible issue，并推进 Todo"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "MTPRO Paper Execution Workflow v1"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "Parent Codex queue preflight rule"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "本 draft 不创建 Linear Project"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "本 draft 不创建 Linear Issues"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "本 draft 不修改 Linear status"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "本 draft 不推进任何 issue 到 Todo"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "完整 issue execution contract 以后以 Linear issue body 为准"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" 'Project 写入 Linear 后，所有 issue 初始必须是 `Backlog / non-executable`'
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "Project 经 Human 确认并写入 Linear 后，由 Parent Codex queue preflight 自动判断唯一 eligible issue，并在 WIP=1、依赖满足、无 active conflict、execution contract 格式完整时推进 Todo"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "不复制维护完整 Linear issue body"
require_contains "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md" "不启动 Symphony"
require_contains "docs/planning/linear-draft-plan.md" "docs/planning/projects/mtpro-paper-execution-workflow-v1-plan.md"
require_contains "docs/planning/linear-draft-plan.md" "MTPRO Paper Execution Workflow v1"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "MTPRO Paper Workflow Control Shell v1"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "Parent Codex queue preflight rule"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "本 draft 不创建 Linear Project"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "本 draft 不创建 Linear Issues"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "本 draft 不修改 Linear status"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "本 draft 不推进任何 issue 到 Todo"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "完整 issue execution contract 以后以 Linear issue body 为准"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" 'Project 写入 Linear 后，所有 issue 初始必须是 `Backlog / non-executable`'
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "Project 经 Human 确认并写入 Linear 后，由 Parent Codex queue preflight 自动判断唯一 eligible issue，并在 WIP=1、依赖满足、无 active conflict、execution contract 格式完整时推进 Todo"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "不复制维护完整 Linear issue body"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "不启动 Symphony"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" '不启动 `@002 / PAR`'
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "不允许 order-level command"
require_contains "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md" "read-model-only Event Timeline / Evidence Explorer"
require_contains "docs/planning/linear-draft-plan.md" "docs/planning/projects/mtpro-paper-workflow-control-shell-v1-plan.md"
require_contains "docs/planning/linear-draft-plan.md" "MTPRO Paper Workflow Control Shell v1"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "MTPRO Market Data Replay Operations v1"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "Parent Codex queue preflight rule"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "本 draft 不创建 Linear Project"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "本 draft 不创建 Linear Issues"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "本 draft 不修改 Linear status"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "本 draft 不推进任何 issue 到 Todo"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "完整 issue execution contract 以后以 Linear issue body 为准"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" 'Project 写入 Linear 后，所有 issue 初始必须是 `Backlog / non-executable`'
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "Project 经 Human 确认并写入 Linear 后，由 Parent Codex queue preflight 自动判断唯一 eligible issue，并在 WIP=1、依赖满足、无 active conflict、execution contract 格式完整时推进 Todo"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "不复制维护完整 Linear issue body"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "不启动 Symphony"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" '不启动 `@002 / PAR`'
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "Binance public read-only market data batch / replay boundary"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "retention / freshness read model"
require_contains "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md" "read-model-only"
require_contains "docs/planning/linear-draft-plan.md" "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md"
require_contains "docs/planning/linear-draft-plan.md" "MTPRO Market Data Replay Operations v1"
require_contains "docs/validation/latest-verification-summary.md" "docs/planning/projects/mtpro-market-data-replay-operations-v1-plan.md"
require_contains "docs/validation/latest-verification-summary.md" "MTPRO Market Data Replay Operations v1"

require_contains "docs/validation/validation-plan.md" "Linear issue execution contract"
require_contains "docs/validation/validation-plan.md" "bash checks/automation-readiness.sh"
require_contains "docs/validation/validation-plan.md" "bash checks/run.sh"
require_contains "docs/validation/validation-plan.md" "Codex / Automation Validation"
require_contains "docs/validation/validation-plan.md" "不引入独立 eval 框架"
require_contains "docs/validation/validation-plan.md" "Finance / Trading Validation"
require_contains "docs/validation/validation-plan.md" "fees / slippage"
require_contains "docs/validation/validation-plan.md" "Backtest / Paper parity"
require_contains "docs/validation/validation-plan.md" "docs/validation/trading-validation-matrix.md"
require_contains "docs/validation/validation-plan.md" "Stage Audit Input Location Rule"
require_contains "docs/validation/validation-plan.md" "docs/audit/inputs/"
require_contains "docs/validation/validation-plan.md" '`docs/validation/` 只保留长期验证入口'
require_contains "docs/validation/validation-plan.md" "MTP-30 Stage Audit Input Validation"
require_contains "docs/validation/validation-plan.md" "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md"
require_contains "docs/validation/validation-plan.md" "MTP-37 Validation Docs / Stage Audit Input Validation"
require_contains "docs/validation/validation-plan.md" "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md"
require_contains "docs/validation/validation-plan.md" "MTP-45 Validation Docs / Stage Audit Input Validation"
require_contains "docs/validation/validation-plan.md" "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md"
require_contains "docs/validation/validation-plan.md" "MTP-53 Validation Docs / Stage Audit Input Validation"
require_contains "docs/validation/validation-plan.md" "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-EMA-PARITY"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-SESSION-LIFECYCLE"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-ACTION-PROPOSAL"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-EXECUTION-WORKFLOW"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-EXECUTION-DECISION"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-ORDER-LIFECYCLE"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-SIMULATED-FILL"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-SESSION-REPLAY"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-ORDER-BOOK-IMBALANCE-PARITY"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-FEES-SLIPPAGE"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-RISK-BLOCKER"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PORTFOLIO-EXPOSURE"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-REPORT-EVIDENCE"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-PAPER-WORKFLOW-CONTROL-SHELL"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-MARKET-DATA-REPLAY-OPERATIONS"
require_contains "docs/validation/trading-validation-matrix.md" "TVM-FUTURE-ISSUE-BACKFILL"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-25"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-30"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-30 阶段收口"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-37"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-37 Paper Session Runtime 阶段收口"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-38"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-39"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-40"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-41"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-42"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-44"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-45"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-47"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-48"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-49"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-52"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-53"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-54"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-55"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-57"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-58"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-59"
require_contains "docs/validation/trading-validation-matrix.md" "PaperWorkflowWorkbenchInformationArchitecture"
require_contains "docs/validation/trading-validation-matrix.md" "PaperSessionLocalControlCommand"
require_contains "docs/validation/trading-validation-matrix.md" "PaperSessionLocalControlEventLogBoundary"
require_contains "docs/validation/trading-validation-matrix.md" "DashboardShellWorkbenchSnapshot"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataBatchReplayBoundary"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataReplayOperationsMetadata"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataBatchReplayContract"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataReplayRetentionPolicy"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataReplayFreshnessEvidenceReadModel"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataReplayBatchFreshnessSummary"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataBatchReplayConsistencyEvidence"
require_contains "docs/validation/trading-validation-matrix.md" "BinanceMarketDataBatchReplayDeterministicParity"
require_contains "docs/validation/trading-validation-matrix.md" "MarketDataReplayProjectionConsistency"
require_contains "docs/validation/trading-validation-matrix.md" "MarketDataReplayProjectionSnapshotConsistencySummary"
require_contains "docs/validation/trading-validation-matrix.md" "MarketDataReplayOperationsEvidenceReadModel"
require_contains "docs/validation/trading-validation-matrix.md" "MarketDataReplayOperationsEvidenceViewModel"
require_contains "docs/validation/trading-validation-matrix.md" "PaperWorkflowEvidenceExplorerSection.marketDataReplayOperation"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayBoundaryDefinesPublicReadOnlyLocalFixtureContract"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayMetadataDefinesDeterministicLocalReplayOperationsEvidence"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayContractBindsMetadataToPublicReadOnlyFixtureBoundary"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayRetentionPolicyComputesFreshStaleExpiredEvidence"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayFreshnessReadModelIsCodableAndHidesSchemaAdapterRuntimeSurface"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayFreshnessSummaryAggregatesRetentionEvidenceDeterministically"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayFixtureParityBuildsDeterministicReplayConsistencyEvidence"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayConsistencyRejectsRecordCountOrderingAndChecksumDrift"
require_contains "docs/validation/trading-validation-matrix.md" "testBatchReplayConsistencyRejectsMetadataAndNetworkBoundaryDrift"
require_contains "docs/validation/trading-validation-matrix.md" "testMarketDataReplayProjectionConsistencyLinksEventLogReplayAndSnapshots"
require_contains "docs/validation/trading-validation-matrix.md" "testMarketDataReplayProjectionConsistencySummaryIsCodableDeterministicAndHidesSchema"
require_contains "docs/validation/trading-validation-matrix.md" "testPaperWorkflowEvidenceExplorerTimelineSnapshotAggregatesReadModelOnlyEvidence"
require_contains "docs/validation/trading-validation-matrix.md" "testDashboardShellSnapshotBindsViewModelSectionsForReadOnlyMacOSShell"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-53 Paper Workflow Control Shell 阶段收口"
require_contains "docs/validation/validation-plan.md" "MTP-47 Paper Workflow Workbench IA / Control Shell Boundary Validation"
require_contains "docs/validation/validation-plan.md" "MTP-48 Paper Session Local Control Command Model Validation"
require_contains "docs/validation/validation-plan.md" "MTP-49 Paper Session Local Control Event Boundary Validation"
require_contains "docs/validation/validation-plan.md" "MTP-52 Dashboard / Workbench Shell Validation"
require_contains "docs/validation/validation-plan.md" "MTP-53 Validation Docs / Stage Audit Input Validation"
require_contains "docs/validation/validation-plan.md" "MTP-54 Binance Market Data Batch / Replay Boundary Validation"
require_contains "docs/validation/validation-plan.md" "MTP-55 Market Data Replay Metadata / Batch Replay Contract Validation"
require_contains "docs/validation/validation-plan.md" "MTP-56 Market Data Replay Retention / Freshness Evidence Validation"
require_contains "docs/validation/validation-plan.md" "MTP-57 Market Data Replay Fixture Parity / Replay Consistency Validation"
require_contains "docs/validation/validation-plan.md" "MTP-58 Market Data Replay Event Log / Projection Consistency Validation"
require_contains "docs/validation/validation-plan.md" "MTP-59 Market Data Replay Report / Dashboard / Event Timeline Evidence Validation"
require_contains "docs/validation/validation-plan.md" 'session-level controls 只允许 `start` / `pause` / `close` / `reset`'
require_contains "docs/contracts/binance-market-data-contract.md" "MTP-54 Market Data Batch / Replay 边界"
require_contains "docs/contracts/binance-market-data-contract.md" "MTP-55 Market Data Replay Metadata / Batch Replay Contract"
require_contains "docs/contracts/binance-market-data-contract.md" "MTP-56 Market Data Replay Retention / Freshness Evidence"
require_contains "docs/contracts/binance-market-data-contract.md" "MTP-57 Market Data Replay Fixture Parity / Replay Consistency"
require_contains "docs/contracts/binance-market-data-contract.md" "MTP-58 Market Data Replay Event Log / Projection Consistency"
require_contains "docs/contracts/binance-market-data-contract.md" "MTP-59 Market Data Replay Operations Report / Dashboard / Event Timeline Evidence"
require_contains "docs/contracts/frontend-view-model-contract.md" "MTP-47 Paper Workflow Workbench IA ViewModel 契约"
require_contains "docs/contracts/frontend-view-model-contract.md" "MTP-52 Dashboard / Workbench Shell ViewModel 契约"
require_contains "docs/contracts/frontend-view-model-contract.md" "MTP-59 Market Data Replay Operations Read Model / ViewModel 契约"
require_contains "docs/contracts/api-contract.md" "MTP-48 Paper Session Local Control Command Model"
require_contains "docs/contracts/api-contract.md" "MTP-49 Paper Session Local Control Event Boundary"
require_contains "docs/contracts/backend-use-case-contract.md" "MTP-48 Paper Session Local Control Command Model Use Case 边界"
require_contains "docs/contracts/backend-use-case-contract.md" "MTP-49 Paper Session Local Control Event Boundary Use Case 边界"
require_contains "docs/product/product-surface-map.md" "MTP-47 Paper workflow Workbench 信息架构和控制壳边界"
require_contains "docs/product/product-surface-map.md" "MTP-48 Paper session 本地控制 Command Model"
require_contains "docs/product/product-surface-map.md" "MTP-49 Paper session 本地控制 Event Boundary"
require_contains "docs/product/product-surface-map.md" "MTP-52 Dashboard / Workbench shell 增量扩展"
require_contains "docs/product/product-surface-map.md" "MTP-55 Market Data Replay Metadata / Batch Replay Contract"
require_contains "docs/product/product-surface-map.md" "MTP-56 Market Data Replay Retention / Freshness Evidence"
require_contains "docs/product/product-surface-map.md" "MTP-57 Market Data Replay Fixture Parity / Replay Consistency"
require_contains "docs/product/product-surface-map.md" "MTP-58 Market Data Replay Event Log / Projection Consistency"
require_contains "docs/product/product-surface-map.md" "MTP-59 Market Data Replay Report / Dashboard / Event Timeline Evidence"
require_contains "Sources/Core/PaperSessionLocalControlCommand.swift" "PaperSessionLocalControlRejectedReason"
require_contains "Sources/Core/PaperSessionLocalControlEventLog.swift" "PaperSessionLocalControlEventLogBoundary"
require_contains "Sources/App/DashboardShell.swift" "DashboardShellWorkbenchSnapshot"
require_contains "Sources/Adapters/BinanceMarketDataBatchReplayBoundary.swift" "BinanceMarketDataBatchReplayBoundary"
require_contains "Sources/Adapters/BinanceMarketDataReplayOperationsMetadata.swift" "BinanceMarketDataReplayOperationsMetadata"
require_contains "Sources/Adapters/BinanceMarketDataReplayOperationsMetadata.swift" "BinanceMarketDataBatchReplayContract"
require_contains "Sources/Adapters/BinanceMarketDataReplayFreshness.swift" "BinanceMarketDataReplayRetentionPolicy"
require_contains "Sources/Adapters/BinanceMarketDataReplayFreshness.swift" "BinanceMarketDataReplayFreshnessEvidenceReadModel"
require_contains "Sources/Adapters/BinanceMarketDataReplayFreshness.swift" "BinanceMarketDataReplayBatchFreshnessSummary"
require_contains "Sources/Adapters/BinanceMarketDataReplayParity.swift" "BinanceMarketDataBatchReplayConsistencyEvidence"
require_contains "Sources/Adapters/BinanceMarketDataReplayParity.swift" "BinanceMarketDataBatchReplayDeterministicParity"
require_contains "Sources/Runtime/MarketDataReplayProjectionConsistency.swift" "MarketDataReplayProjectionConsistency"
require_contains "Sources/Runtime/MarketDataReplayProjectionConsistency.swift" "MarketDataReplayProjectionSnapshotConsistencySummary"
require_contains "Sources/Runtime/MarketDataReplayProjectionConsistency.swift" "MarketDataReplayProjectionSourceContract"
require_contains "Sources/App/MarketDataReplayOperationsEvidence.swift" "MarketDataReplayOperationsEvidenceReadModel"
require_contains "Sources/App/MarketDataReplayOperationsEvidence.swift" "MarketDataReplayOperationsEvidenceViewModel"
require_contains "Sources/App/PaperWorkflowEvidenceExplorer.swift" "marketDataReplayOperation"
require_contains "Sources/App/DashboardShell.swift" "Replay ops"
require_contains "Tests/CoreTests/CoreTests.swift" "testPaperSessionLocalControlValidationRejectsNonSessionOrderAndBrokerCommands"
require_contains "Tests/CoreTests/CoreTests.swift" "testPaperSessionLocalControlEventBoundaryMapsAcceptedCommandsToPaperOnlyFacts"
require_contains "Tests/AppTests/AppTests.swift" "testDashboardShellWorkbenchSnapshotBindsControlsObservabilityAndExplorerReadOnly"
require_contains "Tests/AppTests/AppTests.swift" "MarketDataReplayProjectionConsistencyFixture.deterministicSummary"
require_contains "Tests/AppTests/AppTests.swift" "batch-BTCUSDT-1m-20240101"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayBoundaryForbidsSignedAccountBrokerAndRealOrderCapabilities"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayMetadataRejectsInvalidValuesAndForbiddenCapabilitySurface"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayRetentionPolicyComputesFreshStaleExpiredEvidence"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayFreshnessReadModelIsCodableAndHidesSchemaAdapterRuntimeSurface"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayFreshnessSummaryAggregatesRetentionEvidenceDeterministically"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayFixtureParityBuildsDeterministicReplayConsistencyEvidence"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayConsistencyRejectsRecordCountOrderingAndChecksumDrift"
require_contains "Tests/AdaptersTests/AdaptersTests.swift" "testBatchReplayConsistencyRejectsMetadataAndNetworkBoundaryDrift"
require_contains "Tests/RuntimeTests/RuntimeTests.swift" "testMarketDataReplayProjectionConsistencyLinksEventLogReplayAndSnapshots"
require_contains "Tests/RuntimeTests/RuntimeTests.swift" "testMarketDataReplayProjectionConsistencyRejectsEventLogAndProjectionDrift"
require_contains "docs/validation/trading-validation-matrix.md" "MTP-45 Paper Execution Workflow 阶段收口"
require_contains "docs/validation/trading-validation-matrix.md" "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md"
require_contains "docs/validation/trading-validation-matrix.md" "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md"
require_contains "docs/validation/trading-validation-matrix.md" "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md"
require_contains "docs/validation/trading-validation-matrix.md" "bash checks/run.sh"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "Issue / PR evidence input"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "Trading validation evidence chain"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "Automation readiness evidence"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "Known boundaries"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "Root Docs Delta input"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "Stage Code Audit handoff checklist"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "docs/audit/mtpro-trading-validation-and-parity-hardening-stage-code-audit.md"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "MTP-24"
require_contains "docs/audit/inputs/mtpro-trading-validation-and-parity-hardening-stage-audit-input.md" "MTP-30"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "Issue / PR evidence input"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "Paper runtime validation evidence chain"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "Automation readiness evidence"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "Known boundaries"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "Root Docs Delta input"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "Stage Code Audit handoff checklist"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "docs/audit/mtpro-paper-session-runtime-v1-stage-code-audit.md"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "MTP-31"
require_contains "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md" "MTP-37"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "Issue / PR evidence input"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "Paper execution workflow validation evidence chain"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "Automation readiness evidence"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "Known boundaries"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "Root Docs Delta input"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "Stage Code Audit handoff checklist"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "docs/audit/mtpro-paper-execution-workflow-v1-stage-code-audit.md"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "MTP-38"
require_contains "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md" "MTP-45"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Issue / PR evidence input"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Paper workflow control shell validation evidence chain"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Automation readiness evidence"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Known boundaries"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Root Docs Delta input"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Stage Code Audit handoff checklist"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "docs/audit/mtpro-paper-workflow-control-shell-v1-stage-code-audit.md"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "MTP-47"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "MTP-53"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "Dashboard smoke"
require_contains "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md" "timelineItems=0"
require_contains "docs/validation/eval-strategy.md" "什么时候可以引入独立 eval 框架"
require_contains "docs/validation/latest-verification-summary.md" "Agent / Graphify 默认读取本文档"
require_contains "docs/validation/latest-verification-summary.md" '完整 `verification.md` 只用于审计、追溯和 debug'
require_contains "docs/validation/latest-verification-summary.md" "MTP-30"
require_contains "docs/validation/latest-verification-summary.md" "MTP-37"
require_contains "docs/validation/latest-verification-summary.md" "MTP-53"
require_contains "docs/validation/latest-verification-summary.md" "Linear live-read"
require_contains "docs/validation/latest-verification-summary.md" "bash checks/run.sh"
require_contains "docs/validation/latest-verification-summary.md" "临时 CI 平台边界"
require_contains "docs/validation/latest-verification-summary.md" "覆盖完整 Linear Project"
require_contains "docs/validation/macos-build-run-loop.md" "macOS App shell"

require_contains "docs/audit/mtpro-runtime-research-workbench-v1-stage-code-audit.md" "文档路径"
require_contains "docs/audit/mtpro-runtime-research-workbench-v1-stage-code-audit.md" "命名规则"
require_contains "docs/audit/mtpro-runtime-research-workbench-v1-stage-code-audit.md" "本报告审计完整 Linear Project"
require_contains "docs/audit/mtpro-runtime-research-workbench-v1-stage-code-audit.md" "Known CI Boundary / 临时失败说明"
require_contains "docs/audit/mtpro-runtime-research-workbench-v1-stage-code-audit.md" "无当前遗留 failing PR run"

require_contains "AGENTS.md" "Linear issue 中已填写的 Scope / Non-goals / Codex Instructions / Validation / Boundary / PR Requirements 是 Codex Execution Agent 的执行合同"
require_contains "AGENTS.md" "不二次确认 issue scope"
require_contains "AGENTS.md" "Project Planning Facilitator 只负责阶段规划"
require_contains "AGENTS.md" "active Project pointer"
require_contains "AGENTS.md" '第一个 issue 和后续 issue 的 `Backlog` -> `Todo` 操作都只能由父 Codex'
require_contains "AGENTS.md" "docs/validation/latest-verification-summary.md"
require_contains "AGENTS.md" '完整 `verification.md` 只在审计、追溯或 debug 时读取'
require_contains "AGENTS.md" "详细中文注释"
require_contains "AGENTS.md" "Finance / Trading Domain"
require_contains "AGENTS.md" "Trading validation"
require_contains "AGENTS.md" "Role Alias Rule"
require_contains "AGENTS.md" '@000 = AIE'
require_contains "AGENTS.md" '@001 = PLN'
require_contains "AGENTS.md" "AI Engineer"
require_contains "AGENTS.md" "不替代 Human decision"
require_contains "AGENTS.md" "给 @001 下 Codex 指令"
require_contains "AGENTS.md" "@002 Startup Runbook"
require_contains "AGENTS.md" "执行前检查"
require_contains "AGENTS.md" "pointer 更新后再次执行 queue preview"
require_contains "AGENTS.md" '自动推进唯一 eligible `Backlog` -> `Todo`'
require_contains "AGENTS.md" "Root Docs Delta"
require_contains "AGENTS.md" "Root Docs Refresh Gate"
require_contains "docs/planning/linear-draft-plan.md" "Project Planning Record 命名规则"
require_contains "docs/planning/linear-draft-plan.md" '所有 Project planning record 必须放在 `docs/planning/projects/`'
require_contains "docs/planning/linear-draft-plan.md" '文件名格式：`<linear-project-slug>-plan.md`'
require_contains "docs/planning/linear-draft-plan.md" "slug 使用 Project name 的小写 kebab-case"
require_contains "docs/planning/linear-draft-plan.md" "一个 Linear Project 对应一份 canonical planning record"
require_contains "docs/planning/linear-draft-plan.md" "Project Planning Record 内容规则"
require_contains "docs/planning/linear-draft-plan.md" "Linear write boundary"
require_contains "docs/planning/linear-draft-plan.md" "Repository record boundary"
require_contains "docs/planning/linear-draft-plan.md" "完整 issue execution contract 以 Linear issue body 为准"
require_contains "docs/planning/linear-draft-plan.md" '只有父 Codex 可以操作 `Backlog` -> `Todo`'
require_contains "docs/planning/linear-draft-plan.md" "Root Docs Refresh Gate"
require_contains "docs/planning/linear-draft-plan.md" "Stage Code Audit Report"
require_contains "docs/planning/linear-draft-plan.md" 'Linear Project status 必须设置或确认为 `Completed`'
require_contains "docs/planning/linear-draft-plan.md" 'Linear Project status type 必须是 `completed`'
require_contains "docs/planning/linear-draft-plan.md" 'Linear Project `completedAt` 必须非空'
require_contains "docs/planning/linear-draft-plan.md" 'Human + `@001 / PLN`'
require_contains "docs/planning/linear-draft-plan.md" "docs/planning/projects/mtpro-trading-validation-and-parity-hardening-plan.md"
require_contains "docs/planning/linear-draft-plan.md" "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md"
require_contains "docs/planning/linear-draft-plan.md" "仓库只保存 Project 级计划摘要和格式门槛，不复制维护完整 issue 正文"
require_contains "docs/validation/latest-verification-summary.md" "Root Docs Refresh Gate"
require_contains "docs/validation/latest-verification-summary.md" "Root Docs Delta"
require_contains "docs/validation/latest-verification-summary.md" 'Linear Project status `Completed`'
require_contains "docs/validation/latest-verification-summary.md" 'type=completed'
require_contains "docs/validation/latest-verification-summary.md" 'completedAt'
require_contains "docs/validation/latest-verification-summary.md" "docs/planning/projects/mtpro-paper-session-runtime-v1-plan.md"
require_contains "docs/validation/latest-verification-summary.md" "docs/audit/inputs/"
require_contains "docs/validation/latest-verification-summary.md" "docs/audit/inputs/mtpro-paper-session-runtime-v1-stage-audit-input.md"
require_contains "docs/validation/latest-verification-summary.md" "docs/audit/inputs/mtpro-paper-execution-workflow-v1-stage-audit-input.md"
require_contains "docs/validation/latest-verification-summary.md" "docs/audit/inputs/mtpro-paper-workflow-control-shell-v1-stage-audit-input.md"

require_absent ".github/workflows/checks.yml" "pull_request_target"

printf 'MTPRO automation readiness checks passed.\n'
