name: AEP Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check whitespace
        run: git diff --check

      - name: Run MTPRO checks
        run: bash checks/run.sh
